blank_issues_enabled: false
contact_links:
  - name: QAssistant Chat
    url: https://t.me/QAssistantChat
    about: Our Telegram Bot 
  - name: 提问的智慧
    url: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
    about: 反馈任何问题前请务必阅读
