name: Check Issues

on:
  issues:
    types: [opened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - if: contains(github.event.issue.body, 'ejfweaxptgrsgxed' ) == false
        id: close
        name: Close Issue(template)
        uses: peter-evans/close-issue@v1
        with:
          comment: This issue is being automatically closed because it does not follow the issue template.
